/* eslint-disable sonarjs/no-nested-template-literals */
/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable max-len */
import type { QueryResult } from 'pg';
import fs from 'fs';
import { DBPostgres } from './postgres.js';

// Helper function to check if a column has a default value
function hasDefaultValue(columnDefault: string | null): boolean {
    return columnDefault !== null;
}

export interface GenerateTypesPgOptions {
    host: string;
    user: string;
    password: string;
    db: string;
    logFolder: string;
    outputPath: string;
}

// eslint-disable-next-line complexity
export const generateTypesPg = async (options: GenerateTypesPgOptions) => {
    const DB = DBPostgres.getInstance(
        {
            host: options.host,
            user: options.user,
            password: options.password,
            db: options.db,
            connectionLimit: 3,
            logFolder: options.logFolder
        },
        'generateTypesPg'
    );

    try {
        console.log('Fetching table information...');

        // Get all tables in the public schema
        const tablesResult = (await DB.doQuery({
            queryString: `
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'public'
      AND table_type = 'BASE TABLE'
      ORDER BY table_name;
    `
        })) as QueryResult<{ table_name: string }>;

        const tables = tablesResult.rows.map((row) => row.table_name);

        if (tables.length === 0) {
            console.log('No tables found in the database.');
            await DB.closeConnection();
            return;
        }

        console.log(`Found ${tables.length} tables: ${tables.join(', ')}`);

        let typesFileContent = `/**
 * Auto-generated TypeScript interfaces for PostgreSQL database schema
 * Generated on: ${new Date().toISOString()}
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run the generate-db-types script to regenerate
 */
`;

        // Add date type definitions
        typesFileContent += `
// Date type definitions
export type Year = \`20\${number}\${number}\`;
export type Month = \`0\${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9}\` | \`1\${0 | 1 | 2}\`;
export type Day = \`0\${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9}\` | \`1\${0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9}\` | \`2\${0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9}\` | \`3\${0 | 1}\`;
export type Hour = \`0\${number}\` | \`1\${number}\` | \`2\${0 | 1 | 2 | 3}\`;
export type Minute = \`0\${number}\` | \`\${1 | 2 | 3 | 4 | 5}\${number}\`;
export type Second = \`0\${number}\` | \`\${1 | 2 | 3 | 4 | 5}\${number}\`;
export type DateYMD = \`\${Year}-\${Month}-\${Day}\`;
export type TimeHMS = \`\${Hour}:\${Minute}:\${Second}\`;
export type DateYMDHMS = \`\${DateYMD} \${TimeHMS}\`;

/**
 * Utility Types
 */

/**
 * Type for inserting records - omits fields with default values
 * Each table has a corresponding [TableName]Insert interface
 */
`;

        // Process each table
        for (const tableName of tables) {
            console.log(`Processing table: ${tableName}`);

            // Get column information for the table
            const columnsResult = (await DB.doQuery({
                queryString: `
                SELECT
                  column_name,
                  data_type,
                  is_nullable,
                  column_default
                FROM information_schema.columns
                WHERE table_schema = 'public'
                AND table_name = $1
                ORDER BY ordinal_position;
              `,
                parameters: [tableName]
            })) as QueryResult<{ column_name: string; data_type: string; is_nullable: string; column_default: string }>;

            const columns = columnsResult.rows;

            // Generate TypeScript interface for the table
            const pascalCaseTableName = tableName
                .split('_')
                .map((word: string) => word.charAt(0).toUpperCase() + word.slice(1))
                .join('');

            // Track columns with default values for the Insert interface
            const columnsWithDefaults: string[] = [];

            // Generate the main interface
            typesFileContent += `export interface ${pascalCaseTableName}Row {\n`;

            for (const column of columns) {
                const columnName = column.column_name;
                const isNullable = column.is_nullable === 'YES';
                const nullableSuffix = isNullable ? ' | null' : '';
                const hasDefault = hasDefaultValue(column.column_default);

                // Common auto-generated columns
                const isAutoGenerated = columnName === 'id' || columnName === 'createdAt' || columnName === 'updatedAt' || hasDefault;

                if (isAutoGenerated) {
                    columnsWithDefaults.push(columnName);
                }

                // Map PostgreSQL data types to TypeScript types
                let tsType: string;

                switch (column.data_type.toLowerCase()) {
                    case 'integer':
                    case 'numeric':
                    case 'decimal':
                    case 'real':
                    case 'double precision':
                    case 'smallint':
                    case 'bigint':
                        tsType = 'number';
                        break;
                    case 'boolean':
                        tsType = 'boolean';
                        break;
                    case 'json':
                    case 'jsonb':
                        tsType = 'Record<string, any>';
                        break;
                    case 'timestamp with time zone':
                        tsType = 'Date';
                        break;
                    case 'timestamp without time zone':
                        tsType = 'DateYMDHMS';
                        break;
                    case 'date':
                        tsType = 'Date';
                        break;
                    case 'uuid':
                    case 'character varying':
                    case 'varchar':
                    case 'text':
                    case 'char':
                    case 'character':
                    default:
                        tsType = 'string';
                }

                typesFileContent += `  ${columnName}: ${tsType}${nullableSuffix};\n`;
            }

            typesFileContent += '}\n\n';

            // Generate the Insert interface (omitting columns with default values)
            if (columnsWithDefaults.length > 0) {
                typesFileContent += `/**
 * Insert interface for ${pascalCaseTableName} - omits columns with default values
 */
export interface ${pascalCaseTableName}Insert extends Omit<${pascalCaseTableName}Row, ${columnsWithDefaults.map((col) => `'${col}'`).join(' | ')}> {}\n\n`;
            }
        }

        // Write the generated types to file
        fs.writeFileSync(options.outputPath, typesFileContent);
        console.log(`TypeScript interfaces generated successfully at: ${options.outputPath}`);
    } catch (error) {
        console.error('Error generating TypeScript interfaces:', error);
    } finally {
        await DB.closeConnection();
    }
};
