/* eslint-disable sonarjs/no-nested-template-literals */
/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable max-len */
import type { QueryResult } from 'pg';
import fs from 'fs';
import { DBPostgres } from './postgres.js';

// Helper function to check if a column has a default value that should be omitted
function hasDefaultValueToOmit(columnDefault: string | null): boolean {
    // Don't omit if default is null or 0
    if (columnDefault === null) return false;
    if (columnDefault.startsWith('0.0')) return false;
    if (columnDefault === '0') return false;
    if (columnDefault === 'NULL') return false;
    if (columnDefault?.toLowerCase() === 'null') return false;

    // Otherwise, consider it a default value to omit
    return true;
}

// Interface for enum type information
interface EnumType {
    typeName: string;
    values: string[];
}

export interface GenerateTypesPgOptions {
    host: string;
    user: string;
    password: string;
    db: string;
    logFolder: string;
    outputPath: string;
}

// Function to fetch all enum types and their values from PostgreSQL
async function fetchEnumTypes(DB: DBPostgres): Promise<Map<string, EnumType>> {
    console.log('Fetching enum types...');

    const enumTypesResult = (await DB.doQuery({
        queryString: `
            SELECT
                t.typname AS enum_name,
                array_agg(e.enumlabel ORDER BY e.enumsortorder) AS enum_values
            FROM pg_type t
            JOIN pg_enum e ON t.oid = e.enumtypid
            JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
            WHERE n.nspname = 'public'
            GROUP BY t.typname
        `
    })) as QueryResult<{ enum_name: string; enum_values: string[] }>;

    const enumTypesMap = new Map<string, EnumType>();

    if (enumTypesResult.rows.length > 0) {
        console.log(`Found ${enumTypesResult.rows.length} enum types`);

        for (const row of enumTypesResult.rows) {
            enumTypesMap.set(row.enum_name, {
                typeName: row.enum_name,
                values: row.enum_values
            });
        }
    } else {
        console.log('No enum types found in the database');
    }

    return enumTypesMap;
}

// eslint-disable-next-line complexity, max-statements
export const generateTypesPg = async (options: GenerateTypesPgOptions) => {
    const DB = DBPostgres.getInstance(
        {
            host: options.host,
            user: options.user,
            password: options.password,
            db: options.db,
            connectionLimit: 3,
            logFolder: options.logFolder
        },
        'generateTypesPg'
    );

    try {
        console.log('Fetching table information...');

        // Fetch all enum types and their values
        const enumTypesMap = await fetchEnumTypes(DB);

        // Get all tables in the public schema
        const tablesResult = (await DB.doQuery({
            queryString: `
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'public'
      AND table_type = 'BASE TABLE'
      ORDER BY table_name;
    `
        })) as QueryResult<{ table_name: string }>;

        const tables = tablesResult.rows.map((row) => row.table_name);

        if (tables.length === 0) {
            console.log('No tables found in the database.');
            await DB.closeConnection();
            return;
        }

        console.log(`Found ${tables.length} tables: ${tables.join(', ')}`);

        let typesFileContent = `/**
 * Auto-generated TypeScript interfaces for PostgreSQL database schema
 * Generated on: ${new Date().toISOString()}
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run the generate-db-types script to regenerate
 */
`;

        // Add date type definitions and utility types
        typesFileContent += `
/**
 * Utility type to make specific properties optional
 */
// helper to re-map an intersection back into a fresh object
type Simplify<T> = { [P in keyof T]: T[P] };

type WithOptional<T, K extends keyof T> =
  Simplify< Omit<T, K> & Partial<Pick<T, K>> >;
/**
 * Type for inserting records - makes fields with default values optional
 * Each table has a corresponding [TableName]Insert interface
 */
`;

        // Process each table
        for (const tableName of tables) {
            console.log(`Processing table: ${tableName}`);

            // Get column information for the table, including udt_name for enum types
            const columnsResult = (await DB.doQuery({
                queryString: `
                SELECT
                  column_name,
                  data_type,
                  udt_name,
                  is_nullable,
                  column_default,
                  character_maximum_length
                FROM information_schema.columns
                WHERE table_schema = 'public'
                AND table_name = $1
                ORDER BY ordinal_position;
              `,
                parameters: [tableName]
            })) as QueryResult<{
                column_name: string;
                data_type: string;
                udt_name: string;
                is_nullable: string;
                column_default: string;
                character_maximum_length: number | null;
            }>;

            const columns = columnsResult.rows;

            // Generate TypeScript interface for the table
            const pascalCaseTableName = tableName
                .split('_')
                .map((word: string) => word.charAt(0).toUpperCase() + word.slice(1))
                .join('');

            // Track columns with default values for the Insert interface
            const columnsWithDefaults: string[] = [];

            // Generate the main interface
            typesFileContent += `export interface ${pascalCaseTableName}Row {\n`;

            for (const column of columns) {
                const columnName = column.column_name;
                const isNullable = column.is_nullable === 'YES';
                const nullableSuffix = isNullable ? ' | null' : '';
                const hasDefaultToOmit = hasDefaultValueToOmit(column.column_default);

                // Common auto-generated columns
                const isAutoGenerated = columnName === 'id' || columnName === 'createdAt' || columnName === 'updatedAt' || hasDefaultToOmit;

                if (isAutoGenerated) {
                    columnsWithDefaults.push(columnName);
                }

                // Map PostgreSQL data types to TypeScript types
                let tsType: string;

                // Check if this column is an enum type
                if (column.data_type === 'USER-DEFINED' && enumTypesMap.has(column.udt_name)) {
                    // Get the enum values
                    const enumType = enumTypesMap.get(column.udt_name)!;

                    // Generate a union type of string literals for the enum values
                    tsType = enumType.values.map((value) => `'${value}'`).join(' | ');
                }
                // Special case for TINYINT(1) which is often used as a boolean flag (0 or 1)
                // PostgreSQL doesn't have a native TINYINT type, but it might be defined as a domain or custom type
                // We'll check for smallint with a constraint that limits it to 0 or 1
                else if (
                    (column.data_type.toLowerCase() === 'smallint' || column.data_type.toLowerCase() === 'integer') &&
                    column.column_default !== null &&
                    (column.column_default.includes('0') || column.column_default.includes('1')) &&
                    (column.udt_name.toLowerCase() === 'int2' || column.udt_name.toLowerCase() === 'int4')
                ) {
                    // This is a heuristic - if it's a smallint/integer with a default of 0 or 1,
                    // it's likely being used as a boolean flag
                    tsType = '0 | 1';
                } else {
                    // Handle standard data types
                    switch (column.data_type.toLowerCase()) {
                        case 'integer':
                        case 'numeric':
                        case 'decimal':
                        case 'real':
                        case 'double precision':
                        case 'smallint':
                        case 'bigint':
                            tsType = 'number';
                            break;
                        case 'boolean':
                            tsType = 'boolean';
                            break;
                        case 'json':
                        case 'jsonb':
                            tsType = 'Record<string, any>';
                            break;
                        case 'timestamp with time zone':
                            tsType = 'Date';
                            break;
                        case 'timestamp without time zone':
                            tsType = 'string';
                            break;
                        case 'date':
                            tsType = 'string';
                            break;
                        case 'uuid':
                        case 'character varying':
                        case 'varchar':
                        case 'text':
                        case 'char':
                        case 'character':
                        default:
                            tsType = 'string';
                    }
                }

                typesFileContent += `  ${columnName}: ${tsType}${nullableSuffix};\n`;
            }

            typesFileContent += '}\n\n';

            // Generate the Insert interface (making columns with default values optional)
            if (columnsWithDefaults.length > 0) {
                typesFileContent += `/**
 * Insert interface for ${pascalCaseTableName} - makes columns with default values optional
 */
export type ${pascalCaseTableName}RowInsert = WithOptional<${pascalCaseTableName}Row, ${columnsWithDefaults.map((col) => `'${col}'`).join(' | ')}>\n\n`;
            }
        }

        // Write the generated types to file
        fs.writeFileSync(options.outputPath, typesFileContent);
        console.log(`TypeScript interfaces generated successfully at: ${options.outputPath}`);
    } catch (error) {
        console.error('Error generating TypeScript interfaces:', error);
    } finally {
        await DB.closeConnection();
    }
};
