import type { AiModelCatalogEntry, AiModelCapabilities, AiModelPricing, AiModelSource } from './aiModelTypes.js';

const VERIFIED_AT = '2026-04-19';

const OPENAI_MODELS_SOURCE: AiModelSource = {
    label: 'OpenAI model docs',
    url: 'https://developers.openai.com/api/docs/models',
    verifiedAt: VERIFIED_AT
};

const OPENAI_PRICING_SOURCE: AiModelSource = {
    label: 'OpenAI pricing',
    url: 'https://openai.com/api/pricing/',
    verifiedAt: VERIFIED_AT
};

const ANTHROPIC_MODELS_SOURCE: AiModelSource = {
    label: 'Anthropic models overview',
    url: 'https://platform.claude.com/docs/en/about-claude/models/overview',
    verifiedAt: VERIFIED_AT
};

const ANTHROPIC_PRICING_SOURCE: AiModelSource = {
    label: 'Anthropic pricing',
    url: 'https://platform.claude.com/docs/en/about-claude/pricing',
    verifiedAt: VERIFIED_AT
};

const OPENAI_GPT_5_4_REASONING_LEVELS = ['none', 'low', 'medium', 'high', 'xhigh'] as const;
const OPENAI_GPT_5_REASONING_LEVELS = ['minimal', 'low', 'medium', 'high'] as const;

const createPricing = (pricing: AiModelPricing): AiModelPricing => pricing;

const createCapabilities = (capabilities: AiModelCapabilities): AiModelCapabilities => capabilities;

export const AI_MODEL_CATALOG: readonly AiModelCatalogEntry[] = [
    {
        modelKey: 'openai:gpt-5.4',
        provider: 'openai',
        modelId: 'gpt-5.4',
        snapshotModelId: 'gpt-5.4-2026-03-05',
        aliases: ['gpt-5.4-2026-03-05'],
        displayName: 'GPT-5.4',
        family: 'gpt-5.4',
        description: 'OpenAI flagship model for complex reasoning, coding, and professional workflows.',
        status: 'active',
        recommendedReplacementModelKey: null,
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: true,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: true,
            supportsComputerUse: true,
            supportsMcp: true,
            supportsReasoningEffort: true,
            reasoningEffortLevels: OPENAI_GPT_5_4_REASONING_LEVELS,
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 1_050_000,
        maxOutputTokens: 128_000,
        knowledgeCutoff: '2025-08-31',
        pricing: createPricing({
            inputUsdPerMillionTokens: 2.5,
            cachedInputUsdPerMillionTokens: 0.25,
            outputUsdPerMillionTokens: 15,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: 272_000,
            longContextInputUsdPerMillionTokens: 5,
            longContextCachedInputUsdPerMillionTokens: 0.5,
            longContextOutputUsdPerMillionTokens: 22.5,
            notes: 'Prompts above 272K input tokens are billed at 2x input and 1.5x output for the full session.'
        }),
        sources: [OPENAI_MODELS_SOURCE, OPENAI_PRICING_SOURCE],
        tags: ['recommended', 'reasoning', 'coding', 'agent']
    },
    {
        modelKey: 'openai:gpt-5.4-mini',
        provider: 'openai',
        modelId: 'gpt-5.4-mini',
        snapshotModelId: null,
        aliases: [],
        displayName: 'GPT-5.4 mini',
        family: 'gpt-5.4',
        description: 'Faster, lower-cost GPT-5.4 variant for high-volume agent and coding workloads.',
        status: 'active',
        recommendedReplacementModelKey: null,
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: true,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: true,
            supportsComputerUse: true,
            supportsMcp: true,
            supportsReasoningEffort: true,
            reasoningEffortLevels: OPENAI_GPT_5_4_REASONING_LEVELS,
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 400_000,
        maxOutputTokens: 128_000,
        knowledgeCutoff: '2025-08-31',
        pricing: createPricing({
            inputUsdPerMillionTokens: 0.75,
            cachedInputUsdPerMillionTokens: 0.075,
            outputUsdPerMillionTokens: 4.5,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [OPENAI_MODELS_SOURCE, OPENAI_PRICING_SOURCE],
        tags: ['recommended', 'fast', 'balanced', 'coding', 'agent']
    },
    {
        modelKey: 'openai:gpt-5.4-nano',
        provider: 'openai',
        modelId: 'gpt-5.4-nano',
        snapshotModelId: null,
        aliases: [],
        displayName: 'GPT-5.4 nano',
        family: 'gpt-5.4',
        description: 'Lowest-cost GPT-5.4-class model for simple high-volume workloads and sub-agents.',
        status: 'active',
        recommendedReplacementModelKey: null,
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: true,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: true,
            supportsComputerUse: false,
            supportsMcp: true,
            supportsReasoningEffort: true,
            reasoningEffortLevels: OPENAI_GPT_5_4_REASONING_LEVELS,
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 400_000,
        maxOutputTokens: 128_000,
        knowledgeCutoff: '2025-08-31',
        pricing: createPricing({
            inputUsdPerMillionTokens: 0.2,
            cachedInputUsdPerMillionTokens: 0.02,
            outputUsdPerMillionTokens: 1.25,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [OPENAI_MODELS_SOURCE, OPENAI_PRICING_SOURCE],
        tags: ['recommended', 'cheap', 'classifier', 'subagent']
    },
    {
        modelKey: 'openai:gpt-5.2',
        provider: 'openai',
        modelId: 'gpt-5.2',
        snapshotModelId: 'gpt-5.2-2025-12-11',
        aliases: ['gpt-5.2-2025-12-11'],
        displayName: 'GPT-5.2',
        family: 'gpt-5.2',
        description: 'Previous frontier GPT-5 model still useful for compatibility while migrating to GPT-5.4.',
        status: 'legacy',
        recommendedReplacementModelKey: 'openai:gpt-5.4',
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: true,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: true,
            supportsComputerUse: true,
            supportsMcp: null,
            supportsReasoningEffort: true,
            reasoningEffortLevels: OPENAI_GPT_5_4_REASONING_LEVELS,
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 400_000,
        maxOutputTokens: 128_000,
        knowledgeCutoff: '2025-08-31',
        pricing: createPricing({
            inputUsdPerMillionTokens: 1.75,
            cachedInputUsdPerMillionTokens: 0.175,
            outputUsdPerMillionTokens: 14,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [OPENAI_MODELS_SOURCE, OPENAI_PRICING_SOURCE],
        tags: ['legacy', 'reasoning', 'compatibility']
    },
    {
        modelKey: 'openai:gpt-5.2-chat-latest',
        provider: 'openai',
        modelId: 'gpt-5.2-chat-latest',
        snapshotModelId: 'gpt-5.2-2025-12-11',
        aliases: ['gpt-5.2', 'gpt-5.2-2025-12-11'],
        displayName: 'GPT-5.2 Chat (latest)',
        family: 'gpt-5.2',
        description: 'Chat-oriented alias for GPT-5.2 kept mainly for compatibility with older integrations.',
        status: 'legacy',
        recommendedReplacementModelKey: 'openai:gpt-5.4',
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: true,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: true,
            supportsComputerUse: true,
            supportsMcp: null,
            supportsReasoningEffort: true,
            reasoningEffortLevels: OPENAI_GPT_5_4_REASONING_LEVELS,
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 400_000,
        maxOutputTokens: 128_000,
        knowledgeCutoff: '2025-08-31',
        pricing: createPricing({
            inputUsdPerMillionTokens: 1.75,
            cachedInputUsdPerMillionTokens: 0.175,
            outputUsdPerMillionTokens: 14,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: 'Alias pricing matches GPT-5.2.'
        }),
        sources: [OPENAI_MODELS_SOURCE, OPENAI_PRICING_SOURCE],
        tags: ['legacy', 'alias', 'compatibility']
    },
    {
        modelKey: 'openai:gpt-5.1',
        provider: 'openai',
        modelId: 'gpt-5.1',
        snapshotModelId: null,
        aliases: [],
        displayName: 'GPT-5.1',
        family: 'gpt-5.1',
        description: 'Older GPT-5 generation kept for migrations and backward compatibility.',
        status: 'legacy',
        recommendedReplacementModelKey: 'openai:gpt-5.4',
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: true,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: true,
            supportsComputerUse: true,
            supportsMcp: null,
            supportsReasoningEffort: true,
            reasoningEffortLevels: OPENAI_GPT_5_4_REASONING_LEVELS,
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 400_000,
        maxOutputTokens: 128_000,
        knowledgeCutoff: null,
        pricing: createPricing({
            inputUsdPerMillionTokens: 1.25,
            cachedInputUsdPerMillionTokens: 0.125,
            outputUsdPerMillionTokens: 10,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [OPENAI_MODELS_SOURCE, OPENAI_PRICING_SOURCE],
        tags: ['legacy', 'reasoning', 'compatibility']
    },
    {
        modelKey: 'openai:gpt-5',
        provider: 'openai',
        modelId: 'gpt-5',
        snapshotModelId: null,
        aliases: [],
        displayName: 'GPT-5',
        family: 'gpt-5',
        description: 'Previous GPT-5 model for reasoning and agentic tasks across domains.',
        status: 'legacy',
        recommendedReplacementModelKey: 'openai:gpt-5.1',
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: true,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: true,
            supportsComputerUse: true,
            supportsMcp: null,
            supportsReasoningEffort: true,
            reasoningEffortLevels: OPENAI_GPT_5_REASONING_LEVELS,
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 400_000,
        maxOutputTokens: 128_000,
        knowledgeCutoff: '2024-09-30',
        pricing: createPricing({
            inputUsdPerMillionTokens: 1.25,
            cachedInputUsdPerMillionTokens: 0.125,
            outputUsdPerMillionTokens: 10,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [OPENAI_MODELS_SOURCE, OPENAI_PRICING_SOURCE],
        tags: ['legacy', 'reasoning', 'compatibility']
    },
    {
        modelKey: 'openai:gpt-5-mini',
        provider: 'openai',
        modelId: 'gpt-5-mini',
        snapshotModelId: 'gpt-5-mini-2025-08-07',
        aliases: ['gpt-5-mini-2025-08-07'],
        displayName: 'GPT-5 mini',
        family: 'gpt-5',
        description: 'Lower-cost GPT-5 model kept for compatibility with existing low-latency workloads.',
        status: 'legacy',
        recommendedReplacementModelKey: 'openai:gpt-5.4-mini',
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: true,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: true,
            supportsComputerUse: false,
            supportsMcp: true,
            supportsReasoningEffort: true,
            reasoningEffortLevels: OPENAI_GPT_5_REASONING_LEVELS,
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 400_000,
        maxOutputTokens: 128_000,
        knowledgeCutoff: '2024-05-31',
        pricing: createPricing({
            inputUsdPerMillionTokens: 0.25,
            cachedInputUsdPerMillionTokens: 0.025,
            outputUsdPerMillionTokens: 2,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [OPENAI_MODELS_SOURCE, OPENAI_PRICING_SOURCE],
        tags: ['legacy', 'fast', 'cheap', 'compatibility']
    },
    {
        modelKey: 'openai:gpt-5-nano',
        provider: 'openai',
        modelId: 'gpt-5-nano',
        snapshotModelId: null,
        aliases: [],
        displayName: 'GPT-5 nano',
        family: 'gpt-5',
        description: 'Previous ultra-cheap GPT-5 model retained for small background tasks and compatibility.',
        status: 'legacy',
        recommendedReplacementModelKey: 'openai:gpt-5.4-nano',
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: true,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: true,
            supportsComputerUse: false,
            supportsMcp: null,
            supportsReasoningEffort: true,
            reasoningEffortLevels: OPENAI_GPT_5_REASONING_LEVELS,
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 400_000,
        maxOutputTokens: 128_000,
        knowledgeCutoff: null,
        pricing: createPricing({
            inputUsdPerMillionTokens: 0.05,
            cachedInputUsdPerMillionTokens: 0.005,
            outputUsdPerMillionTokens: 0.4,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [OPENAI_MODELS_SOURCE, OPENAI_PRICING_SOURCE],
        tags: ['legacy', 'cheap', 'background', 'compatibility']
    },
    {
        modelKey: 'openai:gpt-4o-mini',
        provider: 'openai',
        modelId: 'gpt-4o-mini',
        snapshotModelId: null,
        aliases: [],
        displayName: 'GPT-4o mini',
        family: 'gpt-4o',
        description: 'Widely used older low-cost OpenAI model still common in existing apps.',
        status: 'legacy',
        recommendedReplacementModelKey: 'openai:gpt-5.4-mini',
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: true,
            supportsPromptCaching: true,
            supportsWebSearch: null,
            supportsFileSearch: null,
            supportsComputerUse: null,
            supportsMcp: null,
            supportsReasoningEffort: false,
            reasoningEffortLevels: [],
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: null,
        maxOutputTokens: null,
        knowledgeCutoff: null,
        pricing: createPricing({
            inputUsdPerMillionTokens: 0.15,
            cachedInputUsdPerMillionTokens: 0.075,
            outputUsdPerMillionTokens: 0.6,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: 'Kept mainly so older apps can centralize their existing fallback.'
        }),
        sources: [OPENAI_PRICING_SOURCE],
        tags: ['legacy', 'cheap', 'compatibility']
    },
    {
        modelKey: 'openai:o3-deep-research-2025-06-26',
        provider: 'openai',
        modelId: 'o3-deep-research-2025-06-26',
        snapshotModelId: null,
        aliases: [],
        displayName: 'o3 Deep Research (2025-06-26)',
        family: 'o3-deep-research',
        description: 'Specialized OpenAI deep-research model used for long-running research workflows.',
        status: 'specialized',
        recommendedReplacementModelKey: null,
        inputModalities: ['text'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: null,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: null,
            supportsStreaming: null,
            supportsToolCalling: null,
            supportsStructuredOutputs: null,
            supportsPromptCaching: null,
            supportsWebSearch: null,
            supportsFileSearch: null,
            supportsComputerUse: null,
            supportsMcp: null,
            supportsReasoningEffort: null,
            reasoningEffortLevels: [],
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: null,
        maxOutputTokens: null,
        knowledgeCutoff: null,
        pricing: createPricing({
            inputUsdPerMillionTokens: null,
            cachedInputUsdPerMillionTokens: null,
            outputUsdPerMillionTokens: null,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: 'Included to centralize existing app defaults; treat capabilities and pricing as curated manually.'
        }),
        sources: [OPENAI_MODELS_SOURCE],
        tags: ['specialized', 'deep-research']
    },
    {
        modelKey: 'openai:o4-mini-deep-research-2025-06-26',
        provider: 'openai',
        modelId: 'o4-mini-deep-research-2025-06-26',
        snapshotModelId: null,
        aliases: [],
        displayName: 'o4-mini Deep Research (2025-06-26)',
        family: 'o4-mini-deep-research',
        description: 'Smaller specialized OpenAI deep-research model used when lower cost or faster completion is preferred.',
        status: 'specialized',
        recommendedReplacementModelKey: null,
        inputModalities: ['text'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: null,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: null,
            supportsStreaming: null,
            supportsToolCalling: null,
            supportsStructuredOutputs: null,
            supportsPromptCaching: null,
            supportsWebSearch: null,
            supportsFileSearch: null,
            supportsComputerUse: null,
            supportsMcp: null,
            supportsReasoningEffort: null,
            reasoningEffortLevels: [],
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: null,
        maxOutputTokens: null,
        knowledgeCutoff: null,
        pricing: createPricing({
            inputUsdPerMillionTokens: null,
            cachedInputUsdPerMillionTokens: null,
            outputUsdPerMillionTokens: null,
            cacheWrite5mUsdPerMillionTokens: null,
            cacheWrite1hUsdPerMillionTokens: null,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: 'Included to centralize existing app defaults; treat capabilities and pricing as curated manually.'
        }),
        sources: [OPENAI_MODELS_SOURCE],
        tags: ['specialized', 'deep-research', 'fast']
    },
    {
        modelKey: 'anthropic:claude-opus-4-7',
        provider: 'anthropic',
        modelId: 'claude-opus-4-7',
        snapshotModelId: 'claude-opus-4-7',
        aliases: [],
        displayName: 'Claude Opus 4.7',
        family: 'claude-opus-4',
        description: 'Anthropic’s most capable generally available model for complex reasoning and agentic coding.',
        status: 'active',
        recommendedReplacementModelKey: null,
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: null,
            supportsPromptCaching: true,
            supportsWebSearch: null,
            supportsFileSearch: null,
            supportsComputerUse: null,
            supportsMcp: null,
            supportsReasoningEffort: false,
            reasoningEffortLevels: [],
            supportsExtendedThinking: false,
            supportsAdaptiveThinking: true
        }),
        contextWindowTokens: 1_000_000,
        maxOutputTokens: 128_000,
        knowledgeCutoff: '2026-01',
        pricing: createPricing({
            inputUsdPerMillionTokens: 5,
            cachedInputUsdPerMillionTokens: 0.5,
            outputUsdPerMillionTokens: 25,
            cacheWrite5mUsdPerMillionTokens: 6.25,
            cacheWrite1hUsdPerMillionTokens: 10,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: 'Pricing in the latest overview is listed as input, output, and caching rates.'
        }),
        sources: [ANTHROPIC_MODELS_SOURCE, ANTHROPIC_PRICING_SOURCE],
        tags: ['recommended', 'reasoning', 'coding', 'agent']
    },
    {
        modelKey: 'anthropic:claude-sonnet-4-6',
        provider: 'anthropic',
        modelId: 'claude-sonnet-4-6',
        snapshotModelId: 'claude-sonnet-4-6',
        aliases: [],
        displayName: 'Claude Sonnet 4.6',
        family: 'claude-sonnet-4',
        description: 'Balanced Anthropic model combining strong reasoning with lower latency and cost than Opus.',
        status: 'active',
        recommendedReplacementModelKey: null,
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: null,
            supportsPromptCaching: true,
            supportsWebSearch: null,
            supportsFileSearch: null,
            supportsComputerUse: null,
            supportsMcp: null,
            supportsReasoningEffort: false,
            reasoningEffortLevels: [],
            supportsExtendedThinking: true,
            supportsAdaptiveThinking: true
        }),
        contextWindowTokens: 1_000_000,
        maxOutputTokens: 64_000,
        knowledgeCutoff: '2025-08',
        pricing: createPricing({
            inputUsdPerMillionTokens: 3,
            cachedInputUsdPerMillionTokens: 0.3,
            outputUsdPerMillionTokens: 15,
            cacheWrite5mUsdPerMillionTokens: 3.75,
            cacheWrite1hUsdPerMillionTokens: 6,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [ANTHROPIC_MODELS_SOURCE, ANTHROPIC_PRICING_SOURCE],
        tags: ['recommended', 'balanced', 'agent', 'analysis']
    },
    {
        modelKey: 'anthropic:claude-haiku-4-5',
        provider: 'anthropic',
        modelId: 'claude-haiku-4-5',
        snapshotModelId: 'claude-haiku-4-5-20251001',
        aliases: ['claude-haiku-4-5-20251001'],
        displayName: 'Claude Haiku 4.5',
        family: 'claude-haiku-4',
        description: 'Fastest current Anthropic model with near-frontier intelligence for lightweight tasks.',
        status: 'active',
        recommendedReplacementModelKey: null,
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: null,
            supportsPromptCaching: true,
            supportsWebSearch: null,
            supportsFileSearch: null,
            supportsComputerUse: null,
            supportsMcp: null,
            supportsReasoningEffort: false,
            reasoningEffortLevels: [],
            supportsExtendedThinking: true,
            supportsAdaptiveThinking: false
        }),
        contextWindowTokens: 200_000,
        maxOutputTokens: 64_000,
        knowledgeCutoff: '2025-02',
        pricing: createPricing({
            inputUsdPerMillionTokens: 1,
            cachedInputUsdPerMillionTokens: 0.1,
            outputUsdPerMillionTokens: 5,
            cacheWrite5mUsdPerMillionTokens: 1.25,
            cacheWrite1hUsdPerMillionTokens: 2,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [ANTHROPIC_MODELS_SOURCE, ANTHROPIC_PRICING_SOURCE],
        tags: ['recommended', 'fast', 'cheap', 'chat']
    },
    {
        modelKey: 'anthropic:claude-opus-4-6',
        provider: 'anthropic',
        modelId: 'claude-opus-4-6',
        snapshotModelId: 'claude-opus-4-6',
        aliases: [],
        displayName: 'Claude Opus 4.6',
        family: 'claude-opus-4',
        description: 'Prior Anthropic flagship retained for compatibility while moving to Opus 4.7.',
        status: 'legacy',
        recommendedReplacementModelKey: 'anthropic:claude-opus-4-7',
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: null,
            supportsPromptCaching: true,
            supportsWebSearch: null,
            supportsFileSearch: null,
            supportsComputerUse: null,
            supportsMcp: null,
            supportsReasoningEffort: false,
            reasoningEffortLevels: [],
            supportsExtendedThinking: null,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 200_000,
        maxOutputTokens: 128_000,
        knowledgeCutoff: null,
        pricing: createPricing({
            inputUsdPerMillionTokens: 15,
            cachedInputUsdPerMillionTokens: 1.5,
            outputUsdPerMillionTokens: 75,
            cacheWrite5mUsdPerMillionTokens: 18.75,
            cacheWrite1hUsdPerMillionTokens: 30,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [ANTHROPIC_PRICING_SOURCE],
        tags: ['legacy', 'reasoning', 'compatibility']
    },
    {
        modelKey: 'anthropic:claude-3-7-sonnet-20250219',
        provider: 'anthropic',
        modelId: 'claude-3-7-sonnet-20250219',
        snapshotModelId: 'claude-3-7-sonnet-20250219',
        aliases: ['claude-3-7-sonnet-latest'],
        displayName: 'Claude Sonnet 3.7 (20250219)',
        family: 'claude-sonnet-3.7',
        description: 'Older Anthropic reasoning model still found in existing systems.',
        status: 'legacy',
        recommendedReplacementModelKey: 'anthropic:claude-sonnet-4-6',
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: null,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: null,
            supportsComputerUse: null,
            supportsMcp: null,
            supportsReasoningEffort: false,
            reasoningEffortLevels: [],
            supportsExtendedThinking: true,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 200_000,
        maxOutputTokens: 64_000,
        knowledgeCutoff: null,
        pricing: createPricing({
            inputUsdPerMillionTokens: 3,
            cachedInputUsdPerMillionTokens: 0.3,
            outputUsdPerMillionTokens: 15,
            cacheWrite5mUsdPerMillionTokens: 3.75,
            cacheWrite1hUsdPerMillionTokens: 6,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [ANTHROPIC_MODELS_SOURCE, ANTHROPIC_PRICING_SOURCE],
        tags: ['legacy', 'reasoning', 'compatibility']
    },
    {
        modelKey: 'anthropic:claude-3-5-sonnet-20241022',
        provider: 'anthropic',
        modelId: 'claude-3-5-sonnet-20241022',
        snapshotModelId: 'claude-3-5-sonnet-20241022',
        aliases: ['claude-3-5-sonnet-latest'],
        displayName: 'Claude Sonnet 3.5 (20241022)',
        family: 'claude-sonnet-3.5',
        description: 'Legacy balanced Anthropic model still pinned in some apps.',
        status: 'legacy',
        recommendedReplacementModelKey: 'anthropic:claude-sonnet-4-6',
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: null,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: null,
            supportsComputerUse: null,
            supportsMcp: null,
            supportsReasoningEffort: false,
            reasoningEffortLevels: [],
            supportsExtendedThinking: false,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 200_000,
        maxOutputTokens: 8_192,
        knowledgeCutoff: null,
        pricing: createPricing({
            inputUsdPerMillionTokens: 3,
            cachedInputUsdPerMillionTokens: 0.3,
            outputUsdPerMillionTokens: 15,
            cacheWrite5mUsdPerMillionTokens: 3.75,
            cacheWrite1hUsdPerMillionTokens: 6,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [ANTHROPIC_MODELS_SOURCE, ANTHROPIC_PRICING_SOURCE],
        tags: ['legacy', 'balanced', 'compatibility']
    },
    {
        modelKey: 'anthropic:claude-3-5-haiku-20241022',
        provider: 'anthropic',
        modelId: 'claude-3-5-haiku-20241022',
        snapshotModelId: 'claude-3-5-haiku-20241022',
        aliases: ['claude-3-5-haiku-latest'],
        displayName: 'Claude Haiku 3.5 (20241022)',
        family: 'claude-haiku-3.5',
        description: 'Legacy low-cost Anthropic model still pinned in some task routers.',
        status: 'legacy',
        recommendedReplacementModelKey: 'anthropic:claude-haiku-4-5',
        inputModalities: ['text', 'image'],
        outputModalities: ['text'],
        capabilities: createCapabilities({
            supportsTextInput: true,
            supportsTextOutput: true,
            supportsImageInput: true,
            supportsAudioInput: false,
            supportsAudioOutput: false,
            supportsVision: true,
            supportsStreaming: true,
            supportsToolCalling: true,
            supportsStructuredOutputs: null,
            supportsPromptCaching: true,
            supportsWebSearch: true,
            supportsFileSearch: null,
            supportsComputerUse: null,
            supportsMcp: null,
            supportsReasoningEffort: false,
            reasoningEffortLevels: [],
            supportsExtendedThinking: false,
            supportsAdaptiveThinking: null
        }),
        contextWindowTokens: 200_000,
        maxOutputTokens: 8_192,
        knowledgeCutoff: null,
        pricing: createPricing({
            inputUsdPerMillionTokens: 0.8,
            cachedInputUsdPerMillionTokens: 0.08,
            outputUsdPerMillionTokens: 4,
            cacheWrite5mUsdPerMillionTokens: 1,
            cacheWrite1hUsdPerMillionTokens: 1.6,
            longContextThresholdInputTokens: null,
            longContextInputUsdPerMillionTokens: null,
            longContextCachedInputUsdPerMillionTokens: null,
            longContextOutputUsdPerMillionTokens: null,
            notes: null
        }),
        sources: [ANTHROPIC_MODELS_SOURCE, ANTHROPIC_PRICING_SOURCE],
        tags: ['legacy', 'cheap', 'compatibility']
    }
] as const;

